const AbstractToken = Jymfony.Component.Security.Authentication.Token.AbstractToken;

/**
 * AnonymousToken represents an anonymous token.
 *
 * @memberOf Jymfony.Component.Security.Authentication.Token
 */
export default class AnonymousToken extends AbstractToken {
    /**
     * Constructor.
     *
     * @param {string} secret
     * @param {string[]|Jymfony.Component.Security.Role.Role[]} [roles = []]
     */
    __construct(secret, roles = []) {
        super.__construct(roles);

        /**
         * The secret to make sure this token has been generated by this application.
         *
         * @type {string}
         *
         * @private
         */
        this._secret = secret;
        this.authenticated = true;
    }

    /**
     * @inheritdoc
     */
    get credentials() {
        return null;
    }

    /**
     * Gets the token' secret.
     *
     * @returns {string}
     */
    get secret() {
        return this._secret;
    }

    /**
     * @inheritdoc
     */
    __sleep() {
        const fields = super.__sleep();
        fields.push('_secret');

        return fields;
    }
}
