filter:
    excluded_paths:
        - src/*/fixtures/**
        - src/Bundle/*/fixtures/**
        - src/Component/*/fixtures/**
        - src/*/test/**
        - src/Bundle/*/test/**
        - src/Component/*/test/**

tools:
    external_code_coverage:
        timeout: 900

checks:
    javascript: true
