#!/usr/bin/env node

require('@jymfony/autoloader');

const ArgvInput = Jymfony.Component.Console.Input.ArgvInput;
const Kernel = App.Kernel;

const input = new ArgvInput();
const env = input.getParameterOption([ '--env', '-e' ], process.env.APP_ENV ? process.env.APP_ENV : 'dev');
const debug = '0' !== process.env.APP_DEBUG && ! input.hasParameterOption([ '--no-debug', '' ]) && 'prod' !== env;

const kernel = new Kernel(env, debug);
kernel.boot()
    .then(() => {
        const application = kernel.container.get('console.application');
        dd(application);

        return application.run(input);
    }).catch((e) => {
        console.error(e.toString());
    });
