#!/usr/bin/env node

require('@jymfony/autoloader');

const Application = Jymfony.Bundle.FrameworkBundle.Console.Application;
const ArgvInput = Jymfony.Component.Console.Input.ArgvInput;
const Kernel = App.Kernel;

let input = new ArgvInput();
let env = input.getParameterOption([ '--env', '-e' ], process.env.APP_ENV ? process.env.APP_ENV : 'dev');
let debug = '0' !== process.env.APP_DEBUG && ! input.hasParameterOption([ '--no-debug', '' ]) && 'prod' !== env;

let kernel = new Kernel(env, debug);
let application = new Application(kernel);
application.run(input);
