declare namespace Jymfony.Component.Security.Authentication.Token {
    import Role = Jymfony.Component.Security.Role.Role;

    /**
     * AnonymousToken represents an anonymous token.
     */
    export class AnonymousToken extends AbstractToken {
        /**
         * The secret to make sure this token has been generated by this application.
         */
        private _secret: string;

        /**
         * Constructor.
         */
        // @ts-ignore
        __construct(secret: string, roles?: (string | Role)[]): void;
        constructor(secret: string, roles?: (string | Role)[]);

        /**
         * @inheritdoc
         */
        public readonly credentials: null;

        /**
         * Gets the token' secret.
         */
        public readonly secret: string;

        /**
         * @inheritdoc
         */
        __sleep(): string[];
    }
}
